@BASE_URL = http://localhost:4000

### Login
# @name postLogin
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "email": "felipe@fmail.com",
    "senha": "!Senha123"
}

### Salvando token em uma variável
@token = {{postLogin.response.body.token}}

### Registrar usuário
POST {{BASE_URL}}/register
Content-Type: application/json

{
    "nome": "Felipe Barros",
    "email": "felipe2@fmail.com",
    "senha": "!Senha123"
}

### me
GET {{BASE_URL}}/me
Authorization: Bearer {{token}}

### Nova transacao
POST {{BASE_URL}}/transaction
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "Segunda quinzena - Março",
    "descricao": "Salário",
    "valor": 810,
    "data": "2025-03-30",
    "tipo": "income"
}

### Atualizar transacao
PUT {{BASE_URL}}/transaction/90ac199b-a2a0-4012-88c3-1d27aa5de2db
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "titulo": "TESSSSTE",
    "descricao": "Contas",
    "valor": 120.91,
    "data": "2025-03-11",
    "tipo": "expense"
}

### Obter extrato
GET {{BASE_URL}}/transaction/3/2025
Authorization: Bearer {{token}}