@BASE_URL = http://localhost:4000

### Login
# @name postLogin
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "email": "felipe@fmail.com",
    "senha": "123456"
}

### Salvando token em uma variável
@token = {{postLogin.response.body.token}}

### Registrar usuário
POST {{BASE_URL}}/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Felipe Jonathan",
    "email": "felipe2@fmail.com",
    "senha": "123456"
}

### me
POST {{BASE_URL}}/me
Authorization: Bearer {{token}}